concat-service-v1:
  appName: concat-service
  version: v1
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/concat-service
    tag: master

concat-service-v2:
  appName: concat-service
  version: v2
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/concat-service
    tag: feat-canary-2-22ebc6dc9a2b1c3225233cfe29fc2020deb01db5

greeting-service-v1:
  appName: greeting-service
  version: v1
  env:
    - name: CONCAT_SERVICE_URL
      value: http://concat-service:8080/concat
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/greeting-service
    tag: master

istio:
  gatewayName: example-app
  services:
    - name: greeting-service
      gateway: true
      port: 8080
      versions:
        - name: v1
          match:
            - uri:
                prefix: /greeting
            - uri:
                prefix: /login
    - name: concat-service
      gateway: false
      port: 8080
      versions:
        - name: v2
          match:
            - headers:
                cookie:
                  regex: |
                    ^(.*?;)?(email=[^;]*@gmail.com)(;.*)?$
        - name: v1
          match:
            - uri:
                prefix: /concat