concat-service-v1:
  appName: concat-service
  version: v1
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/concat-service
    tag: master

concat-service-v2:
  appName: concat-service
  version: v2
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/concat-service
    tag: feat-canary-a0534d021cadd3bcd66bc8a49f0fa7d1e22f0e78

greeting-service-v1:
  appName: greeting-service
  version: v1
  env:
    - name: CONCAT_SERVICE_URL
      value: http://concat-service/concat
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/greeting-service
    tag: master

istio:
  gatewayName: example-app
  services:
    - name: greeting-service
      host: greeting-service.example-app.svc
      appPort: 8080
      port: 80
      paths:
        - /greeting
    - name: concat-service
      host: concat-service.example-app.svc
      appPort: 8080
      port: 80
      paths:
        - /concat
