apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: concat-service-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.service.port }}
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: concat-service-gwvs
spec:
  hosts:
    - "*"
  gateways:
    - concat-service-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: concat-service
        port:
          number: {{ .Values.service.port }}
