{{- if .Values.route.enabled -}}
{{- $fullName := include "concat-service.fullname" . -}}
{{- $defaultUrl := printf "%s.%s" .Release.Name $.Values.route.defaultDomain -}}
{{- $routePath := .Values.route.path -}}
{{- $host := .Values.route.host -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
{{- if .Values.route.letsencrypt }}
  annotations:
    kubernetes.io/tls-acme: "true"
{{- end }}
  labels:
{{ include "concat-service.labels" . | indent 4 }}
  name: {{ $fullName }}
spec:
  host: {{ default $defaultUrl $host }}
  path: {{ $routePath }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: concat-service
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - routerName: router
{{- end }}