{{ range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .name }}
    labels:
        app: {{ .name }}
        chart: {{ template "istio.chart" $ }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
spec:
    type: {{ default "ClusterIP" .type }}
    ports:
        - port: {{ .appPort }}
          targetPort: {{ .appPort }}
          name: http
    selector:
        app: {{ default .name .appName }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .name }}
spec:
  hosts:
    - "*"
  gateways:
  - {{ template "istio.name" $ }}
{{- if .paths }}
  http:
    - match:
    {{- range .paths }}
      - uri:
          prefix: {{ . }}
    {{- end }}
    {{- end }}
      route:
{{- $service := .}}
{{- range .subsets }}
        - destination:
            host: {{ $service.host }}
            subset: {{ .name }}
            port:
              number: {{ $service.appPort }}
          weight: {{ .weight }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .name }}
spec:
  host: {{ .host }}
  subsets:
{{- range .subsets }}
    - name: {{ .name }}
      labels:
        version: {{ .name }}
{{- end }}
{{- end }}