route:
  enabled: true
  host: example.tld
replicaCount: 1
appPort: 8080
livenessProbePath: actuator/health
readinessProbePath: actuator/health
image:
  repository: joachimprinzbach/greeting-service
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
