apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ template "common.fullname" . }}-destination-rule
  labels:
    chart: {{ template "common.chart" . }}
    release: {{ .Release.Name }}
spec:
  host: "*"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: production
    labels:
      canary: "false"
  - name: canary
    labels:
      canary: "true"