apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "common.name" . }}-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.service.port }}
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "common.name" . }}-gwvs
spec:
  hosts:
    - "*"
  gateways:
    - {{ template "common.name" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ template "common.name" . }}
        port:
          number: {{ .Values.service.port }}
