apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "common.name" . }}
    release: {{ .Release.Name }}
