concat-service-v1: 
  route:
    enabled: true
    host: concat-service.apps.baloise.dev
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/concat-service
    tag: v1
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

concat-service-v2: 
  route:
    enabled: true
    host: concat-service.apps.baloise.dev
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/concat-service
    tag: v2
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
