route:
  enabled: true
  host: greeting-service.apps.baloise.dev
backend:
  replicaCount: 1
  appPort: 8080
  livenessProbePath: actuator/health
  readinessProbePath: actuator/health
  image:
    repository: joachimprinzbach/greeting-service
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
